### ISSUE TITLE
[Q] Highlight some lanelets and route in rviz

### ISSUE THREAD

**Issue by Wing-ka-king** [coincar-sim/lanelet_rviz_plugin_ros#12]
Hey, Where should I begin, if I want to highlight certain lanelets and route calculated by lanelet_routing in rviz?

**Comment by m-naumann** [comment]
I'd recommend to use markers (https://wiki.ros.org/rviz/DisplayTypes/Marker#Line_Strip_.28LINE_STRIP.3D4.29) to visualize a route, at least for the start. 

Since this plugin is intended to display a static map, highlighting routes is not supported. To integrate this feature, you'd need an additional message that provides the information "which lanelets are to be highlighted" to this plugin. I rather see this as a different application, and also implementationwise, I'd recommend writing a separate plugin, once the markers no longer fulfill your needs.
