### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by m-naumann** [coincar-sim/lanelet_rviz_plugin_ros#15]
Hi @orzechow

I got notified that the build failed, maybe you want to watch this repo from now on 😅 

https://github.com/coincar-sim/lanelet_rviz_plugin_ros/runs/2679110720

**Comment by orzechow** [comment]
`Package roslib was not found` looks like fun to debug…

Do you have a good workflow to debug travis CI builds locally, besides manually setting up a similar docker and running all those commands there?

**Comment by orzechow** [comment]
It seems that you can ask Travis to enable debugging for public repos (with SSH access to the container):
https://gist.github.com/francois-blanchard/1564cd9b4220e29b7fb55595cff54f68#gistcomment-2857884

**Comment by orzechow** [comment]
After figuring out that you use a minimal ros installation and let rosdep also install common ROS packages like rosbash, roslib etc. I found the "problem" – rather call it solution :grimacing: 

It turns out that ROS Kinetic has [reached end of life](https://github.com/ros/rosdistro/pull/29529/files) and thus rosdep simply [skips kinetic](https://travis-ci.com/github/coincar-sim/lanelet_rviz_plugin_ros/jobs/508210029#L2857) in the rosdep update step. Somewhat doesn't make sense if we're on a kinetic system, but anyhow, the result is that we're having an empty ROS install within the container:

```
> tree -d 2 /opt/ros/kinetic/
2 [error opening dir]
/opt/ros/kinetic/
├── bin
├── etc
│   └── catkin
│       └── profile.d
├── lib
│   ├── pkgconfig
│   └── python2.7
│       └── dist-packages
│           ├── catkin
│           └── catkin-0.7.29.egg-info
└── share
    ├── catkin
    │   ├── catkin_env_hook
    │   └── cmake
    │       ├── em
    │       ├── env-hooks
    │       ├── platform
    │       ├── symlink_install
    │       ├── templates
    │       ├── test
    │       └── tools
    └── ros_environment
        ├── catkin_env_hook
        └── cmake
```

You can't build any meaningful ROS code with that :wink: 

I'd suggest to drop kinetic support with its EOL now.

**Comment by orzechow** [comment]
See also http://wiki.ros.org/Distributions

**Comment by orzechow** [comment]
Btw. even though you specify some bionic stuff in [.travis.yml](https://github.com/coincar-sim/lanelet_rviz_plugin_ros/blob/release/.travis.yml#L21) both builds were done in xenial (that's why both fail). See #16 for Travis using bionic now.

**Comment by m-naumann** [comment]
> Btw. even though you specify some bionic stuff in [.travis.yml](https://github.com/coincar-sim/lanelet_rviz_plugin_ros/blob/release/.travis.yml#L21) both builds were done in xenial (that's why both fail). See #16 for Travis using bionic now.

Can you double check that? The way it should work is that either a xenial or a bionic docker is used inside the xenial travis machine.

**Comment by orzechow** [comment]
Ah, I was already wondering why this env flag had no effect. But you're right, a docker container is run within the TravisCI container, one with [xenial 16.04](https://travis-ci.com/github/coincar-sim/lanelet_rviz_plugin_ros/jobs/508210029#L207) and one with [bionic 18.04](https://travis-ci.com/github/coincar-sim/lanelet_rviz_plugin_ros/jobs/508210030#L207).
